name: Hello World App

on:
  push:
    branches:
      - 'master'
   
  workflow_dispatch:

jobs:



  build:
    runs-on: ubuntu-latest
    name: Build
    # needs: [codacy-analysis, check-quality]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          cache: 'maven'

      - name:  Maven build
        run: mvn -B package --file pom.xml
        
      - name: Upload a helloworld Artifact
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-artifact
          path: |
            target/*.jar
          if-no-files-found: error
          retention-days: 3     
          
  helloworld-docker-image:
    runs-on: ubuntu-latest
    name: HelloWorld Docker build
    needs: [build]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: helloworld-artifact
          path: target

      - name: Display downloaded artifacts
        run: ls -R
        working-directory: target

      - name: Docker build
        run: docker build -t  ${{ secrets.REGISTRY_USERNAME }}/helloworld:${{ github.sha }} .

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: docker.io       # Server address of Docker registry. If not set then will default to Docker Hub
          username: ${{ secrets.REGISTRY_USERNAME }}    # Username used to log against the Docker registry
          password: ${{ secrets.REGISTRY_PASSWORD }}        # Password or personal access token used to log against the Docker registry

      - name: Docker Push
        run: docker push ${{ secrets.REGISTRY_USERNAME }}/helloworld:${{ github.sha }}

     
 
